# Example GitHub Actions workflow for monorepo package detection
# Save this as .github/workflows/monorepo-ci.yml in your repo root

name: Monorepo CI

on:
  # Trigger on PRs to master
  pull_request:
    branches: [master, main]

  # Trigger on pushes to master
  push:
    branches: [master, main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.detect.outputs.packages }}
      count: ${{ steps.detect.outputs.count }}
      matrix: ${{ steps.detect.outputs.json }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch enough history to compare branches
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: packages/util-git-info

      - name: Detect changed packages
        id: detect
        run: node packages/util-git-info/examples/ci-detect-changed-packages.js

      - name: Display results
        run: |
          echo "Changed packages: ${{ steps.detect.outputs.packages }}"
          echo "Package count: ${{ steps.detect.outputs.count }}"

  # Run tests only for changed packages
  test-changed-packages:
    needs: detect-changes
    if: needs.detect-changes.outputs.count > 0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.detect-changes.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Test ${{ matrix.package }}
        run: |
          if [ -f "packages/${{ matrix.package }}/package.json" ]; then
            cd packages/${{ matrix.package }}
            npm test || echo "No tests defined"
          elif [ -f "components/${{ matrix.package }}/package.json" ]; then
            cd components/${{ matrix.package }}
            npm test || echo "No tests defined"
          fi

      - name: Build ${{ matrix.package }}
        run: |
          if [ -f "packages/${{ matrix.package }}/package.json" ]; then
            cd packages/${{ matrix.package }}
            npm run build || echo "No build script"
          elif [ -f "components/${{ matrix.package }}/package.json" ]; then
            cd components/${{ matrix.package }}
            npm run build || echo "No build script"
          fi

  # Optional: Run full tests on push to master
  full-test-on-master:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run all tests
        run: npm test

  # Skip if no packages changed
  skip-if-no-changes:
    needs: detect-changes
    if: needs.detect-changes.outputs.count == 0
    runs-on: ubuntu-latest

    steps:
      - name: No packages changed
        run: echo "✅ No packages changed, skipping tests"
